import { GitHubClient } from '../github/client';
import { aiReviewer } from '../ai/reviewer';

class ReviewService {
  async reviewPullRequest(
    owner: string,
    repo: string,
    pullNumber: number,
    installationId: number
  ) {
    try {
      const client = new GitHubClient(installationId);

      // Get PR details
      const pr = await client.getPullRequest(owner, repo, pullNumber);
      const files = await client.getPullRequestFiles(owner, repo, pullNumber);

      // Build diff from files
      const diff = files
        .map((file) => {
          return `File: ${file.filename}\nChanges: +${file.additions} -${file.deletions}\n${file.patch || ''}`;
        })
        .join('\n\n');

      // Get AI review
      const review = await aiReviewer.reviewPullRequest(
        pr.title,
        pr.body || '',
        diff
      );

      // Format the review summary
      const riskEmoji = {
        low: '🟢',
        medium: '🟡',
        high: '🔴',
      };

      let reviewBody = `## AI Code Review Summary\n\n`;
      reviewBody += `**Summary:** ${review.summary}\n\n`;
      reviewBody += `**Risk Level:** ${riskEmoji[review.riskLevel]} ${review.riskLevel.toUpperCase()}\n`;
      reviewBody += `**Risk Justification:** ${review.riskJustification}\n\n`;

      if (review.generalComments.length > 0) {
        reviewBody += `### General Comments\n\n`;
        review.generalComments.forEach((comment) => {
          reviewBody += `- ${comment}\n`;
        });
        reviewBody += `\n`;
      }

      reviewBody += `---\n`;
      reviewBody += `*This review was generated by AI. Please review the suggestions carefully.*\n`;
      reviewBody += `*Available commands: \`/ai-review\`, \`/ai-fix-lints\`*`;

      // Prepare inline comments
      const inlineComments = review.inlineComments
        .map((comment) => {
          // Find the file in the changed files
          const file = files.find((f) => f.filename === comment.file);
          if (!file) return null;

          return {
            path: comment.file,
            line: comment.line,
            body: `💡 **AI Suggestion:**\n\n${comment.comment}`,
          };
        })
        .filter((c): c is NonNullable<typeof c> => c !== null);

      // Post review with inline comments
      await client.createReview(
        owner,
        repo,
        pullNumber,
        reviewBody,
        'COMMENT',
        inlineComments
      );

      console.log(`Review posted for PR ${owner}/${repo}#${pullNumber}`);
    } catch (error) {
      console.error('Error reviewing pull request:', error);
      
      // Try to post an error comment
      try {
        const client = new GitHubClient(installationId);
        await client.createIssueComment(
          owner,
          repo,
          pullNumber,
          '❌ Failed to generate AI review. Please check the logs for details.'
        );
      } catch (commentError) {
        console.error('Error posting error comment:', commentError);
      }
    }
  }
}

export const reviewService = new ReviewService();
